# This is a root Argo CD app (App of Apps pattern).
# It tells Argo CD to sync all child apps from the applications folder in Git.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-root
  namespace: argocd # Where this app object is created
  finalizers:
    # Delete child resources first, then delete this app
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default # Argo CD project name
  source:
    repoURL: https://github.com/daws-84s/eks-argocd.git # Git repo with manifests
    targetRevision: main # Branch to watch
    path: applications # Folder to sync from repo
  destination:
    server: https://kubernetes.default.svc # Target Kubernetes cluster
    namespace: argocd # Target namespace
  syncPolicy:
    automated: # Auto-sync from Git
      prune: true # Remove resources deleted in Git
      selfHeal: true # Fix manual changes in cluster
    syncOptions:
      - CreateNamespace=true # Create namespace if missing